# The pinned decoder shifts signed, negative fixed-point intermediates. Preserve
# its two's-complement bit operations using unsigned shifts (no UBSan suppression).
# Generate a build-local copy; do not mutate the external checkout or its license.
function(eaf_sbc_fixups target root)
  set(original "${root}/decoder/srce/synthesis-dct8.c")
  file(READ "${original}" code)
  set(before_y "((y) << 1)")
  set(before_x "(MUL_32S_32S_HI(K, x) << 2)")
  string(FIND "${code}" "${before_y}" found_y)
  string(FIND "${code}" "${before_x}" found_x)
  if(found_y LESS 0 OR found_x LESS 0)
    message(FATAL_ERROR "SBC fixup expects the west.yml-pinned decoder revision")
  endif()
  string(REPLACE "${before_y}" "((int32_t)((uint32_t)(y) << 1))" code "${code}")
  string(REPLACE "${before_x}" "((int32_t)((uint32_t)MUL_32S_32S_HI(K, x) << 2))" code "${code}")
  set(patched "${CMAKE_CURRENT_BINARY_DIR}/eaf-sbc-synthesis-dct8.c")
  file(WRITE "${patched}" "${code}")
  get_target_property(sources ${target} SOURCES)
  list(FIND sources "${original}" index)
  if(index LESS 0)
    message(FATAL_ERROR "SBC target has unexpected source layout")
  endif()
  list(REMOVE_AT sources ${index})
  list(APPEND sources "${patched}")
  set(original8 "${root}/decoder/srce/synthesis-8-generated.c")
  file(READ "${original8}" code8)
  string(REGEX REPLACE "\\(MUL_16S_16S\\(([^)]*)\\)\\) << ([0-9]+)"
    "((int32_t)((uint32_t)MUL_16S_16S(\\1) << \\2))" code8 "${code8}")
  set(patched8 "${CMAKE_CURRENT_BINARY_DIR}/eaf-sbc-synthesis-8.c")
  file(WRITE "${patched8}" "${code8}")
  list(REMOVE_ITEM sources "${original8}")
  list(APPEND sources "${patched8}")
  set(original4 "${root}/decoder/srce/synthesis-sbc.c")
  file(READ "${original4}" code4)
  string(REPLACE "(MUL_16S_32S_HI(K, sample) << 2)"
    "((int32_t)((uint32_t)MUL_16S_32S_HI(K, sample) << 2))" code4 "${code4}")
  set(patched4 "${CMAKE_CURRENT_BINARY_DIR}/eaf-sbc-synthesis.c")
  file(WRITE "${patched4}" "${code4}")
  list(REMOVE_ITEM sources "${original4}")
  list(APPEND sources "${patched4}")
  set_property(TARGET ${target} PROPERTY SOURCES "${sources}")
  if(target STREQUAL "libsbc")
    # Zephyr 4.3's libsbc wrapper uses __packed without including its definition.
    target_compile_options(${target} PRIVATE -include zephyr/toolchain.h)
  endif()
endfunction()
